version: "3"
services:
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.0.6-alpine3.12
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ../redis:/data

  web:
    build:
      context: ../
      dockerfile: docker_rails_env/Dockerfile
    container_name: sportnacja_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ..:/myapp
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
    stdin_open: true
    tty: true

volumes:
  redis:
  postgres:
