version: "3"
services:
  db:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:6.0.6-alpine3.12
    command: redis-server
    volumes:
      - ../redis:/data
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    environment:
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  web:
    build:
      context: ../
      dockerfile: docker_rails_env/Dockerfile
    container_name: sportnacja_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - elasticsearch
    volumes:
      - ..:/myapp
    environment:
      - ELASTICSEARCH_URL=elasticsearch
      - REDIS_URL_CACHING=redis://redis:6379/1
      - REDIS_URL_CABLE=redis://redis:6379/2
    stdin_open: true
    tty: true

volumes:
  elasticsearch:
  redis:
  postgres:
