version: "3"
services:
  redis:
    image: redis:6.0.6-alpine3.12
    container_name: redis
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  db:
    image: postgres:12.3-alpine
    container_name: db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  app:
    build:
      context: ../
      dockerfile: docker_rails_env/Dockerfile
    container_name: sportnacja_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - elasticsearch
    volumes:
      - ..:/sportnacja
    environment:
      - ELASTICSEARCH_URL=elasticsearch
      - REDIS_URL_CACHING=redis://redis:6379/1
      - REDIS_URL_CABLE=redis://redis:6379/2
    stdin_open: true
    tty: true

volumes:
  redis:
  postgres:
  elasticsearch:
