version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  db:
    image: postgres:12.3-alpine
    container_name: db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env_file

  redis:
    image: redis:6.0.6-alpine3.12
    container_name: redis
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379:6379

  sidekiq:
    build:
      context: ../
      dockerfile: docker_rails_env/Dockerfile
    image: sidekiq
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - db
      - redis
      - elasticsearch
    volumes:
      - ..:/sportnacja
    env_file:
      - .env_file

  app:
    build:
      context: ../
      dockerfile: docker_rails_env/Dockerfile
    image: sportnacja_app
    container_name: sportnacja_app
    entrypoint: /usr/bin/entrypoint.sh
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - elasticsearch
    volumes:
      - ..:/sportnacja
    env_file:
      - .env_file
    stdin_open: true
    tty: true

volumes:
  redis:
  postgres:
  elasticsearch:
